#!/bin/sh
# Copyright (C) Carlos Guerra

# [root@HOME-CLOUD snmp]# sensors
# acpitz-virtual-0
# Adapter: Virtual device
# temp1:        +27.8°C  (crit = +110.0°C)
# temp2:        +29.8°C  (crit = +110.0°C)
#
# coretemp-isa-0000
# Adapter: ISA adapter
# Package id 0: +105.0°C  (high = +105.0°C, crit = +105.0°C)
# Core 0:       +103.0°C  (high = +105.0°C, crit = +105.0°C)
# Core 1:       +105.0°C  (high = +105.0°C, crit = +105.0°C)
#
# iwlwifi-virtual-0
# Adapter: Virtual device
# temp1:        +81.0°C
#
# nct6776-isa-0a00
# Adapter: ISA adapter
# Vcore:                  +1.58 V  (min =  +0.00 V, max =  +1.74 V)
# in1:                    +1.37 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
# AVCC:                   +3.33 V  (min =  +2.98 V, max =  +3.63 V)
# +3.3V:                  +3.31 V  (min =  +2.98 V, max =  +3.63 V)
# in4:                    +1.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
# in5:                    +0.00 V  (min =  +0.00 V, max =  +0.00 V)
# in6:                    +0.13 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
# 3VSB:                   +3.30 V  (min =  +2.98 V, max =  +3.63 V)
# Vbat:                   +3.25 V  (min =  +2.70 V, max =  +3.63 V)
# fan1:                     0 RPM  (min =    0 RPM)
# fan2:                     0 RPM  (min =    0 RPM)
# SYSTIN:                 +27.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
# CPUTIN:                 +86.5°C  (high = +80.0°C, hyst = +75.0°C)  ALARM  sensor = CPU diode
# AUXTIN:                 +83.0°C  (high = +80.0°C, hyst = +75.0°C)  ALARM  sensor = CPU diode
# PCH_CHIP_CPU_MAX_TEMP:  +98.0°C  (high = +80.0°C, hyst = +75.0°C)
# PECI Agent 0:          +104.0°C  (high = +80.0°C, hyst = +75.0°C)
#                                  (crit = +105.0°C)
# PCH_CHIP_TEMP:           +0.0°C
# PCH_CPU_TEMP:            +0.0°C
# intrusion0:            OK
# intrusion1:            OK

# [root@HOME-CLOUD snmp]# sh sensors-fans
# 0


/usr/bin/sensors | /bin/grep '^fan1:' | /bin/sed 's/^.*: *\([0-9]*\) RPM .*$/\1/'
